# Generated by Django 3.1 on 2020-08-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_dataset_file_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
